---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.16.4
  customize:
    natdnshostresolver1: "on"
    memory: 2048
provisioner: chef_zero

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode_ubuntu-14.04_chef-provisionerless
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
- name: default
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::default]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: system
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::system]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: mysql
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_aptly::repos]
    - recipe[optoro_metrics::mysql]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: kafka
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_metrics::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::kafka]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: memcached 
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_metrics::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::memcached]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: elasticsearch
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_metrics::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::elasticsearch]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: redis
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_metrics::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::redis]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: rabbitmq
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_metrics::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::rabbitmq]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: mongodb
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_metrics::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::mongodb]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: zookeeper
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_metrics::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::zookeeper]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
- name: openvpn
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_metrics::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_metrics::openvpn]
  attributes:
    optoro:
      aptly_url: 'aptly.optoro.io'
